[package]
name = "fit-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copyless = "0.1.5"
binrw = { version = "0.13.0" }
paste = "1.0"